name: Deployment - Development

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  deploy:
    uses: bkan0n/bkan0n-deploy-workflow/.github/workflows/main.yml@main
    with:
      environment: development
      docker_compose_file: docker-compose.dev.yaml
    secrets: inherit
